version: '3.8'
services:
  freight-frontend:
    build: ./frontend  
    ports:
      - "5173:5173"
    depends_on:
      - freight 
  freight:
    build: ./  
    ports:
      - "5000:5000" 
    extra_hosts:
      - "host.docker.internal:host-gateway"